services:

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: postgres:9.4
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"